- name: Build and Run Maven App
  hosts: localhost
  tasks:
    - name: Ensure Maven is available
      command: mvn --version
      environment:
        JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64

    - name: Run Maven build
      command: mvn clean install
      args:
        chdir: "/mnt/c/Users/Neer/Desktop/practice/myapp"
      environment:
        JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64

    - name: Run Maven-built JAR
      command: java -jar target/myapp-1.0-SNAPSHOT.jar
      args:
        chdir: "/mnt/c/Users/Neer/Desktop/practice/myapp"
      environment:
        JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
